db:
  image: kiasaki/alpine-postgres:9.5
  container_name: sonar-db
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    - POSTGRES_DB=sonar

sonarqube:
  # image: kajnelissen/sonarqube-alpine-php:latest
  build: ./sonar-web
  container_name: sonar-web  
  links:
    - db
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
  volumes:
    - ./code:/var/www/html/code
  ports:
    - "9000:9000"
    - "9002:9002"


